[[stack]]
name = "servarr"
tags = ["media", "automation", "servarr"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/servarr/docker-compose.yaml",
]

environment = """
# User and group configuration
PUID=[[OP__KOMODO__COMMON__PUID]]
PGID=[[OP__KOMODO__COMMON__PGID]]
TZ=[[TZ]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]

# Port configuration
PORT_PROWLARR_HTTP=[[PORT_PROWLARR_HTTP]]
PORT_OVERSEERR_HTTP=[[PORT_OVERSEERR_HTTP]]
PORT_QBITTORRENT_HTTP=[[PORT_QBITTORRENT_HTTP]]
PORT_QBITTORRENT_TORRENTING=[[PORT_QBITTORRENT_TORRENTING]]
PORT_RADARR_HTTP=[[PORT_RADARR_HTTP]]
PORT_SONARR_HTTP=[[PORT_SONARR_HTTP]]

# Version tags
PROWLARR_TAG=latest
OVERSEERR_TAG=latest
QBITTORRENT_TAG=latest
RADARR_TAG=latest
SONARR_TAG=latest

# API authentication tokens
PROWLARR_API_AUTH_TOKEN=[[OP__KOMODO__SERVARR__PROWLARR_API_AUTH_TOKEN]]
RADARR_API_AUTH_TOKEN=[[OP__KOMODO__SERVARR__RADARR_API_AUTH_TOKEN]]
SONARR_API_AUTH_TOKEN=[[OP__KOMODO__SERVARR__SONARR_API_AUTH_TOKEN]]
PLEX_AUTH_TOKEN=[[OP__KOMODO__SERVARR__PLEX_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[OP__KOMODO__COMMON__HOME_NAS_IP]]
"""