[[stack]]
name = "servarr"
tags = ["media", "automation", "servarr"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/homelab-komodo-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/servarr/docker-compose.yaml",
]

environment = """
# User and group configuration
PUID=[[PUID]]
PGID=[[PGID]]
TZ=[[TZ]]

# Configuration directory
CONFIGDIR=[[CONFIGDIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[DOMAIN]]
HOST_NAME=[[HOST_NAME]]
TAILNET=[[TAILNET]]

# Port configuration
PORT_PROWLARR_HTTP=[[PORT_PROWLARR_HTTP]]
PORT_OVERSEERR_HTTP=[[PORT_OVERSEERR_HTTP]]
PORT_QBITTORRENT_HTTP=[[PORT_QBITTORRENT_HTTP]]
PORT_QBITTORRENT_TORRENTING=[[PORT_QBITTORRENT_TORRENTING]]
PORT_RADARR_HTTP=[[PORT_RADARR_HTTP]]
PORT_SONARR_HTTP=[[PORT_SONARR_HTTP]]

# Version tags
PROWLARR_TAG=[[PROWLARR_TAG]]
OVERSEERR_TAG=[[OVERSEERR_TAG]]
QBITTORRENT_TAG=[[QBITTORRENT_TAG]]
RADARR_TAG=[[RADARR_TAG]]
SONARR_TAG=[[SONARR_TAG]]

# API authentication tokens
PROWLARR_API_AUTH_TOKEN=[[PROWLARR_API_AUTH_TOKEN]]
RADARR_API_AUTH_TOKEN=[[RADARR_API_AUTH_TOKEN]]
SONARR_API_AUTH_TOKEN=[[SONARR_API_AUTH_TOKEN]]
PLEX_AUTH_TOKEN=[[PLEX_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[NAS_IP]]
"""