[[stack]]
name = "servarr"
tags = ["media", "automation", "servarr"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/servarr/docker-compose.yaml",
]

environment = """
# User and group configuration
PUID=[[PUID]]
PGID=[[PGID]]
TZ=[[TZ]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]

# Port configuration
PORT_PROWLARR_HTTP=9696
PORT_OVERSEERR_HTTP=5055
PORT_QBITTORRENT_HTTP=8080
PORT_QBITTORRENT_TORRENTING=6881
PORT_RADARR_HTTP=7878
PORT_SONARR_HTTP=8989

# Version tags
PROWLARR_TAG=latest
OVERSEERR_TAG=latest
QBITTORRENT_TAG=latest
RADARR_TAG=latest
SONARR_TAG=latest

# API authentication tokens
PROWLARR_API_AUTH_TOKEN=[[PROWLARR_API_AUTH_TOKEN]]
RADARR_API_AUTH_TOKEN=[[RADARR_API_AUTH_TOKEN]]
SONARR_API_AUTH_TOKEN=[[SONARR_API_AUTH_TOKEN]]
PLEX_AUTH_TOKEN=[[PLEX_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[NAS_IP]]
"""