[[stack]]
name = "tautulli"
tags = ["media", "monitoring", "plex"]

[stack.config]
server = "docker-home"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/tautulli/docker-compose.yaml",
]

environment = """
# User and group configuration
PUID=[[OP__KOMODO__COMMON__PUID]]
PGID=[[OP__KOMODO__COMMON__PGID]]
TZ=[[TZ]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
PORT_TAUTULLI_HTTP=8181

# API configuration
TAUTULLI_API_AUTH_TOKEN=[[OP__KOMODO__TAUTULLI__TAUTULLI_API_AUTH_TOKEN]]
"""