name: "vps_reverse_proxy"

services:
####################
# VPS Reverse Proxy
####################

  caddy:
    container_name: caddy-vps
    build:
      context: ${REPODIR}/services/admin/caddy-build
      dockerfile: Dockerfile
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - ${PORT_CADDY_HTTP}:80
      - ${PORT_CADDY_HTTPS}:443
      - ${PORT_CADDY_HTTPS}:443/udp
      - ${PORT_CADDY_ADMIN}:2019
    volumes:
      - ${REPODIR}/services/admin/vps/caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CONFIGDIR}/caddy-vps/data:/data
      - ${CONFIGDIR}/caddy-vps/config:/config
    labels:
      - homepage.group=Administration
      - homepage.name=Caddy VPS
      - homepage.icon=caddy.svg
      - homepage.description=VPS Main Router
      - homepage.widget.type=caddy
      - homepage.widget.url=http://localhost:${PORT_CADDY_ADMIN}
    env_file:
      - ${REPODIR}/docker.env
    healthcheck:
      test: ["CMD", "caddy", "version"]
    restart: unless-stopped

networks:
  default:
    name: caddy-net
    external: true