[[stack]]
name = "caddy-sequoia"
tags = ["proxy", "reverse-proxy", "sequoia", "caddy"]

[stack.config]
server = "docker-seq"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
run_directory = "services/caddy"
branch = "main"
reclone = false
file_paths = [
    "docker-compose.yaml",
    "sequoia/docker-compose.yaml",
]

environment = """
# Caddy instance identifier for data/config directories
CADDY_INSTANCE=sequoia

# Caddy version for build
CADDY_VERSION=[[CADDY_VERSION]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
ADMIN_DOMAIN=[[OP__KOMODO__COMMON__ADMIN_DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]

# Port configuration
PORT_AUTHENTIK_HTTP=[[PORT_AUTHENTIK_HTTP]]
PORT_CADDY_HTTP=[[PORT_CADDY_HTTP]]
PORT_CADDY_HTTPS=[[PORT_CADDY_HTTPS]]
PORT_CADDY_ADMIN=[[PORT_CADDY_ADMIN]]

# Cloudflare API token for DNS challenges
CF_API_TOKEN=[[OP__KOMODO__CADDY__CF_API_TOKEN]]
"""