[[stack]]
name = "nebula-sync-sequoia"
tags = ["pihole", "dns", "networking", "sequoia"]

[stack.config]
server = "docker-seq"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
run_directory = "services/nebula-sync"
file_paths = [
    "docker-compose.yaml",
    "sequoia/docker-compose.yaml",
]

environment = """
# System configuration
TZ=[[TZ]]

# Network configuration
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]

# Pi-hole credentials for Sequoia
SEQUOIA_PIHOLE_1_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__SEQUOIA_PIHOLE_1_APP_PASSWORD]]
SEQUOIA_PIHOLE_2_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__SEQUOIA_PIHOLE_2_APP_PASSWORD]]
"""