[[stack]]
name = "stirlingpdf"
tags = ["pdf", "document", "utility"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/homelab-komodo-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/stirlingpdf/docker-compose.yaml",
]

environment = """
# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Network and domain configuration
DOMAIN=[[DOMAIN]]
PORT_STIRLING_HTTP=8082

# OAuth2 configuration for Authentik integration
STIRLING_OAUTH_ISSUER=[[STIRLING_OAUTH_ISSUER]]
STIRLING_OAUTH_CLIENT_ID=[[STIRLING_OAUTH_CLIENT_ID]]
STIRLING_OAUTH_CLIENT_SECRET=[[STIRLING_OAUTH_CLIENT_SECRET]]
"""