[[stack]]
name = "caddy-home"
tags = ["proxy", "reverse-proxy", "home", "caddy"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/caddy/docker-compose.yaml",
    "services/caddy/home/docker-compose.yaml",
]

environment = """
# Caddy instance identifier for data/config directories
CADDY_INSTANCE=caddy-home

# Caddy version for build
CADDY_VERSION=[[CADDY_VERSION]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network configuration
HOST_NAME=[[HOST_NAME]]
TAILNET=[[TAILNET]]

# Port configuration
PORT_CADDY_HTTP=[[PORT_CADDY_HTTP]]
PORT_CADDY_HTTPS=[[PORT_CADDY_HTTPS]]
PORT_CADDY_ADMIN=[[PORT_CADDY_ADMIN]]

# Cloudflare API token for DNS challenges
CF_API_TOKEN=[[OP__KOMODO__CADDY__CF_API_TOKEN]]
"""