[[stack]]
name = "proxy-vps"
tags = ["docker", "security", "proxy", "socket"]

[stack.config]
server = "homelab-vps"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/proxy/docker-compose.yaml",
]

environment = """
PROXY_INSTANCE=vps
# System configuration
TZ=[[TZ]]

# Port configuration
PORT_SOCKY_PROXY=[[PORT_SOCKY_PROXY]]
"""