[[stack]]
name = "immich"
tags = ["media", "photos"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/immich/docker-compose.yaml",
]

environment = """
# System configuration
TZ=[[TZ]]
CONFIG_DIR=[[CONFIG_DIR]]

# Version configuration
IMMICH_TAG=latest

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]
PORT_IMMICH_HTTP=2283

# Database configuration
IMMICH_DB_USERNAME=[[OP__KOMODO__IMMICH__IMMICH_DB_USERNAME]]
IMMICH_DB_PASSWORD=[[OP__KOMODO__IMMICH__IMMICH_DB_PASSWORD]]
IMMICH_DB_DATABASE_NAME=[[OP__KOMODO__IMMICH__IMMICH_DB_DATABASE_NAME]]

# API tokens
IMMICH_API_AUTH_TOKEN=[[OP__KOMODO__IMMICH__IMMICH_API_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[OP__KOMODO__COMMON__HOME_NAS_IP]]
"""