[[stack]]
name = "immich"
tags = ["media", "photos", "ai"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/homelab-komodo-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/immich/docker-compose.yaml",
]

environment = """
# Database configuration
IMMICH_DB_USERNAME=[[IMMICH_DB_USERNAME]]
IMMICH_DB_PASSWORD=[[IMMICH_DB_PASSWORD]]
IMMICH_DB_DATABASE_NAME=[[IMMICH_DB_DATABASE_NAME]]

# API tokens
IMMICH_API_AUTH_TOKEN=[[IMMICH_API_AUTH_TOKEN]]

# System configuration
TZ=[[TZ]]
CONFIGDIR=[[CONFIGDIR]]

# Network and domain configuration
DOMAIN=[[DOMAIN]]
HOST_NAME=[[HOST_NAME]]
TAILNET=[[TAILNET]]
PORT_IMMICH_HTTP=[[PORT_IMMICH_HTTP]]

# Storage configuration
NAS_IP=[[NAS_IP]]

# Version configuration
IMMICH_TAG=[[IMMICH_TAG]]
"""