[[stack]]
name = "immich"
tags = ["media", "photos"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
run_directory = "services/immich"
branch = "main"
reclone = false
file_paths = [
    "docker-compose.yaml",
]

environment = """
# System configuration
TZ=[[TZ]]

# Version configuration
IMMICH_TAG=release

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]
PORT_IMMICH_HTTP=[[PORT_IMMICH_HTTP]]

# Database configuration
IMMICH_DB_DATABASE_NAME=immich
IMMICH_DB_USERNAME=postgres
IMMICH_DB_PASSWORD=[[OP__KOMODO__IMMICH__IMMICH_DB_PASSWORD]]

# API tokens
IMMICH_API_AUTH_TOKEN=[[OP__KOMODO__IMMICH__IMMICH_API_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[OP__KOMODO__COMMON__HOME_NAS_IP]]
DB_DATA_LOCATION=[[CONFIG_DIR]]/immich2/postgres
"""