[[stack]]
name = "proxy-sequoia-rpi"
tags = ["docker", "security", "proxy", "socket", "sequoia"]

[stack.config]
server = "sequoia-rpi-4"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
linked_repo = "app-stacks"
env_file_path = ".env.proxy-sequoia-rpi"
file_paths = [
    "services/proxy/docker-compose.yaml",
    "services/proxy/remote/docker-compose.yaml",
]

environment = """
PROXY_INSTANCE=sequoia-rpi
# System configuration
TZ=[[TZ]]

# Port configuration
PORT_SOCKY_PROXY=[[PORT_SOCKY_PROXY]]
"""
