name: "monitoring-docker"

services:
  beszel-agent:
    image: "henrygd/beszel-agent:0.19.0"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: ${PORT_BESZEL_LISTEN}
      KEY: ${BESZEL_AGENT_KEY}
      DOCKER_HOST: ${BESZEL_DOCKER_HOST:?BESZEL_DOCKER_HOST is required}
