---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- search:
    provider: [brave, google, duckduckgo]
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short