name: "dashboard"
services:

####################
# Dashboard
####################

  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_TAG:-latest}
    container_name: homepage
    logging:
      driver: ${LOGGING_DRIVER:-local}
    networks:
      - socky_proxy-net
    ports:
      - ${PORT_DASH_HTTP}:3000
    environment:
      - PUID=${PUID}
      - PGI=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - HOMEPAGE_VAR_ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_VAR_TAILNET=${TAILNET}
      - HOMEPAGE_VAR_PORT_SOCKY_PROXY=${PORT_SOCKY_PROXY}
      - HOMEPAGE_VAR_PORT_PROXMOX_HTTPS=${PORT_PROXMOX_HTTPS}
      - HOMEPAGE_VAR_SUSANOO_MONITORING_USER=${SUSANOO_MONITORING_USER}
      - HOMEPAGE_VAR_SUSANOO_MONITORING_TOKEN=${SUSANOO_MONITORING_TOKEN}
      - HOMEPAGE_VAR_TRUENAS_SCALE_TOKEN=${TRUENAS_SCALE_HOMEPAGE_TOKEN}
      - HOMEPAGE_VAR_EURUS_MONITORING_USER=${EURUS_MONITORING_USER}
      - HOMEPAGE_VAR_EURUS_MONITORING_TOKEN=${EURUS_MONITORING_TOKEN}
      - HOMEPAGE_VAR_PORT_ZEPHYRUS_HTTP=${PORT_ZEPHYRUS_HTTP}
      - HOMEPAGE_VAR_ZEPHYRUS_REMOTE_STATS_PASSWORD=${ZEPHYRUS_REMOTE_STATS_PASSWORD}
      - HOMEPAGE_VAR_HOMEASSISTANT_KEY=${HOMEASSISTANT_KEY}
      - HOMEPAGE_VAR_HOMEASSISTANT_SEQ_KEY=${HOMEASSISTANT_SEQ_KEY}
      - HOMEPAGE_VAR_HOMEASSISTANT_KALASZ_KEY=${HOMEASSISTANT_KALASZ_KEY}
      - HOMEPAGE_VAR_PORT_PLEX_HTTP=${PORT_PLEX_HTTP}
      - HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_HOMEPAGE_TOKEN}
      - HOMEPAGE_VAR_PIHOLE_1_APP_PASSWORD=${PIHOLE_1_APP_PASSWORD}
      - HOMEPAGE_VAR_PIHOLE_2_APP_PASSWORD=${PIHOLE_2_APP_PASSWORD}
      - HOMEPAGE_VAR_SEQUOIA_PIHOLE_1_APP_PASSWORD=${SEQUOIA_PIHOLE_1_APP_PASSWORD}
      - HOMEPAGE_VAR_SEQUOIA_PIHOLE_2_APP_PASSWORD=${SEQUOIA_PIHOLE_2_APP_PASSWORD}
    volumes:
      - ${REPODIR}/services/homepage/config:/app/config
    restart: unless-stopped

networks:
  socky_proxy-net:
    name: socky_proxy-net
    external: true