name: "dashboard"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_TAG:-latest}
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - HOMEPAGE_VAR_ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_VAR_TAILNET=${TAILNET}
      - HOMEPAGE_VAR_PORT_SOCKY_PROXY=${PORT_SOCKY_PROXY}
      - HOMEPAGE_VAR_PORT_PROXMOX_HTTPS=${PORT_PROXMOX_HTTPS}
      - HOMEPAGE_VAR_SUSANOO_MONITORING_USER=${SUSANOO_MONITORING_USER}
      - HOMEPAGE_VAR_SUSANOO_MONITORING_TOKEN=${SUSANOO_MONITORING_TOKEN}
      - HOMEPAGE_VAR_TRUENAS_SCALE_TOKEN=${TRUENAS_SCALE_HOMEPAGE_TOKEN}
      - HOMEPAGE_VAR_EURUS_MONITORING_USER=${EURUS_MONITORING_USER}
      - HOMEPAGE_VAR_EURUS_MONITORING_TOKEN=${EURUS_MONITORING_TOKEN}
      - HOMEPAGE_VAR_PORT_ZEPHYRUS_HTTP=${PORT_ZEPHYRUS_HTTP}
      - HOMEPAGE_VAR_ZEPHYRUS_REMOTE_STATS_PASSWORD=${ZEPHYRUS_REMOTE_STATS_PASSWORD}
      - HOMEPAGE_VAR_HOMEASSISTANT_KEY=${HOMEASSISTANT_KEY}
      - HOMEPAGE_VAR_HOMEASSISTANT_SEQ_KEY=${HOMEASSISTANT_SEQ_KEY}
      - HOMEPAGE_VAR_HOMEASSISTANT_KALASZ_KEY=${HOMEASSISTANT_KALASZ_KEY}
      - HOMEPAGE_VAR_PORT_PLEX_HTTP=${PORT_PLEX_HTTP}
      - HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_HOMEPAGE_TOKEN}
      - HOMEPAGE_VAR_TECHNITIUM_1_API_TOKEN=${TECHNITIUM_1_API_TOKEN}
      - HOMEPAGE_VAR_TECHNITIUM_2_API_TOKEN=${TECHNITIUM_2_API_TOKEN}
      - HOMEPAGE_VAR_TECHNITIUM_SEQ_1_API_TOKEN=${TECHNITIUM_SEQ_1_API_TOKEN}
      - HOMEPAGE_VAR_TECHNITIUM_SEQ_2_API_TOKEN=${TECHNITIUM_SEQ_2_API_TOKEN}
    volumes:
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - vps-ingress
      - monitoring-control
    restart: unless-stopped
    labels:
      - kuma.homepage.http.name=Homepage
      - kuma.homepage.http.url=http://homepage:3000
      - kuma.homepage.http.interval=60
      - kuma.__site="homepage"

networks:
  vps-ingress:
    external: true
    name: vps-ingress
  monitoring-control:
    external: true
    name: monitoring-control
