[[stack]]
name = "homepage"
tags = ["dashboard", "homepage", "monitoring"]

[stack.config]
server = "homelab-vps"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/homepage/docker-compose.yaml",
]
config_files = [
  { path = "services/homepage/config/docker.yaml" },
  { path = "services/homepage/config/services.yaml" },
  { path = "services/homepage/config/settings.yaml" },
  { path = "services/homepage/config/widgets.yaml" }
]
environment = """
# User and group configuration
PUID=[[OP__KOMODO__COMMON__PUID]]
PGID=[[OP__KOMODO__COMMON__PGID]]
TZ=[[TZ]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Application configuration
HOMEPAGE_TAG=latest
HOMEPAGE_ALLOWED_HOSTS=[[OP__KOMODO__HOMEPAGE__HOMEPAGE_ALLOWED_HOSTS]]

# Network and domain configuration
ADMIN_DOMAIN=[[OP__KOMODO__COMMON__ADMIN__DOMAIN]]
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]
PORT_DASH_HTTP=[[PORT_DASH_HTTP]]
PORT_SOCKY_PROXY=[[PORT_SOCKY_PROXY]]

# Proxmox configuration
PORT_PROXMOX_HTTPS=[[PORT_PROXMOX_HTTPS]]
SUSANOO_MONITORING_USER=[[OP__KOMODO__HOMEPAGE__SUSANOO_MONITORING_USER]]
SUSANOO_MONITORING_TOKEN=[[OP__KOMODO__HOMEPAGE__SUSANOO_MONITORING_TOKEN]]
EURUS_MONITORING_USER=[[OP__KOMODO__HOMEPAGE__EURUS_MONITORING_USER]]
EURUS_MONITORING_TOKEN=[[OP__KOMODO__HOMEPAGE__EURUS_MONITORING_TOKEN]]

# TrueNAS configuration
TRUENAS_SCALE_HOMEPAGE_TOKEN=[[OP__KOMODO__HOMEPAGE__TRUENAS_SCALE_HOMEPAGE_TOKEN]]

# Synology configuration
PORT_ZEPHYRUS_HTTP=[[PORT_ZEPHYRUS_HTTP]]
ZEPHYRUS_REMOTE_STATS_PASSWORD=[[OP__KOMODO__HOMEPAGE__ZEPHYRUS_REMOTE_STATS_PASSWORD]]

# Home Assistant configuration
HOMEASSISTANT_KEY=[[OP__KOMODO__HOMEPAGE__HOMEASSISTANT_KEY]]
HOMEASSISTANT_SEQ_KEY=[[OP__KOMODO__HOMEPAGE__HOMEASSISTANT_SEQ_KEY]]
HOMEASSISTANT_KALASZ_KEY=[[OP__KOMODO__HOMEPAGE__HOMEASSISTANT_KALASZ_KEY]]

# Plex configuration
PORT_PLEX_HTTP=[[PORT_PLEX_HTTP]]
PLEX_HOMEPAGE_TOKEN=[[OP__KOMODO__HOMEPAGE__PLEX_HOMEPAGE_TOKEN]]

# Pi-hole configuration
PIHOLE_1_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__PIHOLE_1_APP_PASSWORD]]
PIHOLE_2_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__PIHOLE_2_APP_PASSWORD]]
SEQUOIA_PIHOLE_1_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__SEQUOIA_PIHOLE_1_APP_PASSWORD]]
SEQUOIA_PIHOLE_2_APP_PASSWORD=[[OP__KOMODO__HOMEPAGE__SEQUOIA_PIHOLE_2_APP_PASSWORD]]
"""