[[stack]]
name = "ntfy"
tags = ["monitoring", "notifications"]

[stack.config]
server = "homelab-vps"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
linked_repo = "app-stacks"
file_paths = [
    "services/ntfy/docker-compose.yaml",
]

environment = """
# System configuration
TZ=[[TZ]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]

# Port configuration
PORT_NTFY_HTTP=[[PORT_NTFY_HTTP]]
"""
