name: "nebula-sync"

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://pihole1.${TAILNET}|${PIHOLE_1_APP_PASSWORD}
    - REPLICAS=http://main-pi-zero-2.${TAILNET}|${PIHOLE_2_APP_PASSWORD}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    - TZ=${TZ}
    - CLIENT_SKIP_TLS_VERIFICATION=true