name: "zigbee2mqtt"

services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT_ZIGBEE2MQTT:-8085}:8080  # <Host Port>:<Container Port>