[[stack]]
name = "authentik"
tags = ["authentication", "identity", "sso"]

[stack.config]
server = "vps-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/homelab-komodo-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/authentik/docker-compose.yaml",
]

environment = """
# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Network and domain configuration
DOMAIN=[[DOMAIN]]

# Port configuration
PORT_AUTHENTIK_HTTP=[[PORT_AUTHENTIK_HTTP]]
PORT_AUTHENTIK_HTTPS=[[PORT_AUTHENTIK_HTTPS]]

# Application configuration
AUTHENTIK_IMAGE=ghcr.io/goauthentik/server
AUTHENTIK_TAG=2025.8.1
AUTHENTIK_HOMEPAGE_TOKEN=[[AUTHENTIK_HOMEPAGE_TOKEN]]

# Database configuration
AUTHENTIK_PG_DB=[[AUTHENTIK_PG_DB]]
AUTHENTIK_PG_USER=[[AUTHENTIK_PG_USER]]
AUTHENTIK_PG_PASS=[[AUTHENTIK_PG_PASS]]

# Secret key
AUTHENTIK_SECRET_KEY=[[AUTHENTIK_SECRET_KEY]]

# Email configuration
AUTHENTIK_EMAIL__HOST=[[AUTHENTIK_EMAIL__HOST]]
AUTHENTIK_EMAIL__PORT=[[AUTHENTIK_EMAIL__PORT]]
AUTHENTIK_EMAIL__USERNAME=[[AUTHENTIK_EMAIL__USERNAME]]
AUTHENTIK_EMAIL__PASSWORD=[[AUTHENTIK_EMAIL__PASSWORD]]
AUTHENTIK_EMAIL__USE_TLS=[[AUTHENTIK_EMAIL__USE_TLS]]
AUTHENTIK_EMAIL__USE_SSL=[[AUTHENTIK_EMAIL__USE_SSL]]
AUTHENTIK_EMAIL__TIMEOUT=[[AUTHENTIK_EMAIL__TIMEOUT]]
AUTHENTIK_EMAIL__FROM=[[AUTHENTIK_EMAIL__FROM]]
"""