[[stack]]
name = "auth"
tags = ["authentication", "identity", "sso"]

[stack.config]
server = "homelab-vps"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/authentik/docker-compose.yaml",
]

environment = """
# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]

# Port configuration
PORT_AUTHENTIK_HTTP=9000
PORT_AUTHENTIK_HTTPS=9443

# Application configuration
AUTHENTIK_IMAGE=ghcr.io/goauthentik/server
AUTHENTIK_TAG=2025.8.1
AUTHENTIK_HOMEPAGE_TOKEN=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_HOMEPAGE_TOKEN]]

# Database configuration
AUTHENTIK_PG_DB=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_PG_DB]]
AUTHENTIK_PG_USER=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_PG_USER]]
AUTHENTIK_PG_PASS=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_PG_PASS]]

# Secret key
AUTHENTIK_SECRET_KEY=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_SECRET_KEY]]

# Email configuration
AUTHENTIK_EMAIL__HOST=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__HOST]]
AUTHENTIK_EMAIL__PORT=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__PORT]]
AUTHENTIK_EMAIL__USERNAME=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__USERNAME]]
AUTHENTIK_EMAIL__PASSWORD=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__PASSWORD]]
AUTHENTIK_EMAIL__USE_TLS=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__USE_TLS]]
AUTHENTIK_EMAIL__USE_SSL=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__USE_SSL]]
AUTHENTIK_EMAIL__TIMEOUT=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__TIMEOUT]]
AUTHENTIK_EMAIL__FROM=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_EMAIL__FROM]]
"""