[[stack]]
name = "paperless"
tags = ["documents", "ocr", "management"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/paperless/docker-compose.yaml",
]

environment = """
# System configuration
TZ=[[TZ]]

# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]
PORT_PAPERLESS_HTTP=[[PORT_PAPERLESS_HTTP]]

# Database configuration
PAPERLESS_DB_NAME=[[OP__KOMODO__PAPERLESS__PAPERLESS_DB_NAME]]
PAPERLESS_DB_USER=[[OP__KOMODO__PAPERLESS__PAPERLESS_DB_USER]]
PAPERLESS_DB_PASSWORD=[[OP__KOMODO__PAPERLESS__PAPERLESS_DB_PASSWORD]]

# Application configuration
PAPERLESS_SECRETKEY=[[OP__KOMODO__PAPERLESS__PAPERLESS_SECRETKEY]]
PAPERLESS_URL=[[OP__KOMODO__PAPERLESS__PAPERLESS_URL]]
PAPERLESS_SOCIALACCOUNT_PROVIDERS=[[OP__KOMODO__PAPERLESS__PAPERLESS_SOCIALACCOUNT_PROVIDERS]]
PAPERLESS_API_AUTH_TOKEN=[[OP__KOMODO__PAPERLESS__PAPERLESS_API_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[OP__KOMODO__COMMON__HOME_NAS_IP]]
"""