[[stack]]
name = "paperless"
tags = ["documents", "ocr", "management"]

[stack.config]
server = "home-server"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/paperless/docker-compose.yaml",
]

environment = """
# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# System configuration
TZ=[[TZ]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[TAILNET]]
PORT_PAPERLESS_HTTP=8000

# Database configuration
PAPERLESS_DB_NAME=[[PAPERLESS_DB_NAME]]
PAPERLESS_DB_USER=[[PAPERLESS_DB_USER]]
PAPERLESS_DB_PASSWORD=[[PAPERLESS_DB_PASSWORD]]

# Application configuration
PAPERLESS_SECRETKEY=[[PAPERLESS_SECRETKEY]]
PAPERLESS_URL=[[PAPERLESS_URL]]
PAPERLESS_SOCIALACCOUNT_PROVIDERS=[[PAPERLESS_SOCIALACCOUNT_PROVIDERS]]
PAPERLESS_API_AUTH_TOKEN=[[PAPERLESS_API_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[NAS_IP]]
"""