[[stack]]
name = "actualbudget"
tags = ["finance", "personal", "budgeting"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
git_account = "brumi1024"
repo = "brumi1024/komodo-app-stacks"
run_directory="services/actualbudget"
file_paths = [
  "docker-compose.yaml"
]

environment = """
# Configuration directory
CONFIG_DIR=[[CONFIG_DIR]]

# Application configuration
ACTUALBUDGET_TAG=latest
TZ=[[TZ]]

# Logging configuration
LOGGING_DRIVER=[[LOGGING_DRIVER]]

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
PORT_ACTUAL_HTTP=[[PORT_ACTUAL_HTTP]]
"""